-- Generated by hypr2lua-web.
-- Source: hyprland.conf

local activeBorderColor = {
  colors = { "rgba(151515ee)", "rgba(5e6650ee)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(51573b66)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 2,
    gaps_out = 2,
    border_size = 2,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    shadow = {
      enabled = true,
      render_power = 3,
      range = 16,
      color = "rgba(00000052)",
      color_inactive = "rgba(00000028)",
    },
  },
})
