# TheGreek
# Theme create by: https://github.com/HANCORE-linux/omarchy-whitegold-theme
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "thegreek"

# ========= Border =========
file_panel_border = "#3E4135" # Overlay0
sidebar_border = "#242424"    # Base
footer_border = "#3E4135"     # Overlay0

# ========= Border Active =========
file_panel_border_active = "#363a34" # Lavendar
sidebar_border_active = "#4B0304"    # Red
footer_border_active = "#4D574E"     # Green
modal_border_active = "#5E6349"      # Overlay2

# ========= Background (bg) =========
full_screen_bg = "#D0D0C8" # Base
file_panel_bg = "#D0D0C8"  # Base
sidebar_bg = "#D0D0C8"     # Base
footer_bg = "#D0D0C8"      # Base
modal_bg = "#D0D0C8"       # Base

# ========= Foreground (fg) =========
full_screen_fg = "#242424" # Subtext0
file_panel_fg = "#242424"  # Subtext0
sidebar_fg = "#242424"     # Subtext0
footer_fg = "#242424"      # Subtext0
modal_fg = "#242424"       # Subtext0

# ========= Special Color =========
cursor = "#3B3B3B"  # Rosewater
correct = "#4D574E" # Green
error = "#4B0304"   # Red
hint = "#F05A0F"    # Sapphire
cancel = "#2E311A"  # Maroon
# Gradient color can only have two color!
gradient_color = ["#242424", "#DE6A41"] # [Blue, Mauve]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#4D574E" # Green
file_panel_top_path = "#3B3B3B"           # Blue
file_panel_item_selected_fg = "#D0D0C8"   # Sky
file_panel_item_selected_bg = "#242424"   # Base

# ========= Sidebar Special Items =========
sidebar_title = "#DE6A41"            # Sapphire
sidebar_item_selected_fg = "#D0D0C8" # Sky
sidebar_item_selected_bg = "#242424" # Base
sidebar_divider = "#5E6349"          # Overlay2

# ========= Modal Special Items =========
modal_cancel_fg = "#D0D0C8" # Surface0
modal_cancel_bg = "#2E311A" # Maroon

modal_confirm_fg = "#D0D0C8" # Surface0
modal_confirm_bg = "#464943" # Sky

# ========= Help Menu =========
help_menu_hotkey = "#464943" # Sky
help_menu_title = "#2E311A"  # Maroon
